use anyhow::{bail, Result};
use serde::{Deserialize, Serialize};
use std::{fs, path::Path};

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct Theme { pub version: u32, pub name: String, pub colors: Colors, pub typography: Typography, pub spacing: u32, pub radius: u32, pub border_width: u32, pub shadow: String, pub artwork_style: String, pub control_style: String }
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)] pub struct Colors { pub background: String, pub surface: String, pub text: String, pub accent: String, pub border: String }
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)] pub struct Typography { pub family: String, pub size: u32 }
impl Theme {
    pub fn neutral() -> Self { Self { version: 1, name: "Neutral".into(), colors: Colors { background: "#202428".into(), surface: "#2b3136".into(), text: "#edf1f3".into(), accent: "#75a7a0".into(), border: "#55616a".into() }, typography: Typography { family: "Sans Serif".into(), size: 15 }, spacing: 12, radius: 6, border_width: 1, shadow: "subtle".into(), artwork_style: "square".into(), control_style: "rounded".into() } }
}
pub fn starters() -> Vec<Theme> { let n = Theme::neutral(); let mut winamp = n.clone(); winamp.name="Winamp-inspired".into(); winamp.colors=Colors{background:"#18204a".into(),surface:"#37447c".into(),text:"#ffffff".into(),accent:"#f5b91d".into(),border:"#8ca0d8".into()}; let mut terminal=n.clone(); terminal.name="Terminal green".into(); terminal.colors=Colors{background:"#051307".into(),surface:"#0d2811".into(),text:"#b5ffb9".into(),accent:"#42ee72".into(),border:"#298548".into()}; let mut mono=n.clone(); mono.name="Monochrome".into(); mono.colors=Colors{background:"#1e1e1e".into(),surface:"#303030".into(),text:"#eeeeee".into(),accent:"#aaaaaa".into(),border:"#777777".into()}; let mut contrast=n; contrast.name="High contrast".into(); contrast.colors=Colors{background:"#000000".into(),surface:"#000000".into(),text:"#ffffff".into(),accent:"#ffff00".into(),border:"#ffffff".into()}; vec![Theme::neutral(),winamp,terminal,mono,contrast] }
pub fn load(path: &Path) -> Result<Vec<Theme>> { Ok(if path.exists() { serde_json::from_slice(&fs::read(path)?)? } else { starters() }) }
pub fn save(path: &Path, themes: &[Theme]) -> Result<()> { if let Some(parent)=path.parent(){fs::create_dir_all(parent)?}; let temp=path.with_extension("json.tmp"); fs::write(&temp, serde_json::to_vec_pretty(themes)?)?; fs::rename(temp,path)?; Ok(()) }
pub fn import_json(input: &str) -> Result<Theme> { let theme: Theme=serde_json::from_str(input)?; validate(&theme)?; Ok(theme) }
pub fn validate(theme: &Theme) -> Result<()> { if theme.version != 1 { bail!("unsupported theme version") } if theme.name.trim().is_empty() { bail!("theme name is required") } for color in [&theme.colors.background,&theme.colors.surface,&theme.colors.text,&theme.colors.accent,&theme.colors.border] { if !valid_color(color) { bail!("invalid color token: {color}") } } Ok(()) }
fn valid_color(value: &str) -> bool { value.len()==7 && value.starts_with('#') && value[1..].chars().all(|c|c.is_ascii_hexdigit()) }
#[cfg(test)] mod tests { use super::*; #[test] fn import_and_export_are_validated(){let t=Theme::neutral(); let json=serde_json::to_string(&t).unwrap(); assert_eq!(import_json(&json).unwrap(),t); assert!(import_json(r##"{"version":1,"name":"bad","colors":{"background":"pink","surface":"#000000","text":"#000000","accent":"#000000","border":"#000000"},"typography":{"family":"x","size":1},"spacing":1,"radius":1,"border_width":1,"shadow":"x","artwork_style":"x","control_style":"x"}"##).is_err());} #[test] fn theme_round_trip(){let p=std::env::temp_dir().join("ahoy-themes-test.json");save(&p,&starters()).unwrap();assert_eq!(load(&p).unwrap().len(),5);let _=fs::remove_file(p);} }
